; generated by PrusaSlicer 2.7.1+linux-x64-GTK3 on 2023-12-21 at 15:09:08 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M190 S50 ; set bed temperature and wait for it to be reached
M104 S220 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S220 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F7800
G1 E-2 F2400
G92 E0
G1 X89.021 Y-10.739 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:0.561339
G1 F1800
G1 X89.081 Y-10.739 E2.00259
;WIDTH:0.601217
G1 X89.141 Y-10.739 E2.00538
;WIDTH:0.641095
G1 X89.201 Y-10.739 E2.00836
G1 X89.221 Y-10.819 E2.01246
;WIDTH:0.601217
G1 X89.241 Y-10.899 E2.01629
;WIDTH:0.561339
G1 X89.261 Y-10.979 E2.01984
;WIDTH:0.52146
G1 X89.261 Y-49.021 E3.53356
;WIDTH:0.562512
G1 X89.24 Y-49.121 E3.53797
;WIDTH:0.603564
G1 X89.22 Y-49.22 E3.54268
G1 X89.121 Y-49.24 E3.54739
;WIDTH:0.562512
G1 X89.021 Y-49.261 E3.5518
;WIDTH:0.52146
G1 X16.261 Y-49.261 E6.44698
G1 X16.261 Y-49.739 E6.466
G1 X89.021 Y-49.739 E9.36118
;WIDTH:0.562512
G1 X89.36 Y-49.719 E9.37585
;WIDTH:0.603564
G1 X89.698 Y-49.698 E9.39164
G1 X89.698 Y-49.418 E9.40469
G1 X89.719 Y-49.22 E9.41397
;WIDTH:0.562512
G1 X89.739 Y-49.021 E9.42261
;WIDTH:0.52146
G1 X89.739 Y-10.979 E10.93633
;WIDTH:0.561339
G1 X89.719 Y-10.819 E10.94328
;WIDTH:0.601217
G1 X89.699 Y-10.66 E10.95072
;WIDTH:0.641095
G1 X89.679 Y-10.5 E10.95874
G1 X89.699 Y-10.34 E10.96676
;WIDTH:0.601217
G1 X89.719 Y-10.181 E10.9742
;WIDTH:0.561339
G1 X89.739 Y-10.021 E10.98115
;WIDTH:0.52146
G1 X89.739 Y49.021 E13.33048
;WIDTH:0.525085
G1 X89.737 Y49.105 E13.33385
;WIDTH:0.564325
G1 X89.718 Y49.401 E13.34671
;WIDTH:0.603564
G1 X89.698 Y49.698 E13.36059
G1 X89.36 Y49.719 E13.37638
;WIDTH:0.562512
G1 X89.021 Y49.739 E13.39105
;WIDTH:0.52146
G1 X30.979 Y49.739 E15.70059
;WIDTH:0.561339
G1 X30.819 Y49.719 E15.70754
;WIDTH:0.601217
G1 X30.66 Y49.699 E15.71498
;WIDTH:0.641095
G1 X30.5 Y49.679 E15.723
G1 X30.34 Y49.699 E15.73102
;WIDTH:0.601217
G1 X30.181 Y49.719 E15.73846
;WIDTH:0.561339
G1 X30.021 Y49.739 E15.74541
;WIDTH:0.52146
G1 X-9.021 Y49.739 E17.29892
;WIDTH:0.561339
G1 X-9.181 Y49.719 E17.30587
;WIDTH:0.601217
G1 X-9.34 Y49.699 E17.31331
;WIDTH:0.641095
G1 X-9.5 Y49.679 E17.32133
G1 X-9.66 Y49.699 E17.32935
;WIDTH:0.601217
G1 X-9.819 Y49.719 E17.33679
;WIDTH:0.561339
G1 X-9.979 Y49.739 E17.34374
;WIDTH:0.52146
G1 X-89.021 Y49.739 E20.48888
;WIDTH:0.562513
G1 X-89.36 Y49.719 E20.50355
;WIDTH:0.603565
G1 X-89.698 Y49.698 E20.51934
G1 X-89.719 Y49.36 E20.53513
;WIDTH:0.562513
G1 X-89.739 Y49.021 E20.5498
;WIDTH:0.52146
G1 X-89.739 Y4.979 E22.30226
;WIDTH:0.561339
G1 X-89.719 Y4.819 E22.30921
;WIDTH:0.601217
G1 X-89.699 Y4.66 E22.31665
;WIDTH:0.641095
G1 X-89.679 Y4.5 E22.32467
G1 X-89.699 Y4.34 E22.33269
;WIDTH:0.601217
G1 X-89.719 Y4.181 E22.34013
;WIDTH:0.561339
G1 X-89.739 Y4.021 E22.34708
;WIDTH:0.52146
G1 X-89.739 Y-49.021 E24.45766
;WIDTH:0.562513
G1 X-89.719 Y-49.36 E24.47233
;WIDTH:0.603565
G1 X-89.698 Y-49.698 E24.48812
G1 X-89.36 Y-49.719 E24.50391
;WIDTH:0.562513
G1 X-89.021 Y-49.739 E24.51858
;WIDTH:0.52146
G1 X-9.979 Y-49.739 E27.66372
;WIDTH:0.562512
G1 X-9.64 Y-49.719 E27.67839
;WIDTH:0.603564
G1 X-9.302 Y-49.698 E27.69418
G1 X-9.281 Y-49.36 E27.70997
;WIDTH:0.562512
G1 X-9.261 Y-49.021 E27.72464
;WIDTH:0.52146
G1 X-9.261 Y-30.261 E28.47111
G1 X-9.739 Y-30.261 E28.49013
G1 X-9.739 Y-49.021 E29.2366
;WIDTH:0.562512
G1 X-9.76 Y-49.121 E29.24101
;WIDTH:0.603564
G1 X-9.78 Y-49.22 E29.24572
G1 X-9.879 Y-49.24 E29.25043
;WIDTH:0.562512
G1 X-9.979 Y-49.261 E29.25484
;WIDTH:0.52146
G1 X-89.021 Y-49.261 E32.39998
;WIDTH:0.562513
G1 X-89.121 Y-49.24 E32.40439
;WIDTH:0.603565
G1 X-89.22 Y-49.22 E32.4091
G1 X-89.24 Y-49.121 E32.41381
;WIDTH:0.562513
G1 X-89.261 Y-49.021 E32.41822
;WIDTH:0.52146
G1 X-89.261 Y4.021 E34.5288
;WIDTH:0.561339
G1 X-89.241 Y4.101 E34.53235
;WIDTH:0.601217
G1 X-89.221 Y4.181 E34.53618
;WIDTH:0.641095
G1 X-89.201 Y4.261 E34.54028
G1 X-89.141 Y4.261 E34.54326
;WIDTH:0.601217
G1 X-89.081 Y4.261 E34.54605
;WIDTH:0.561339
G1 X-89.021 Y4.261 E34.54864
;WIDTH:0.52146
G1 X-72.261 Y4.261 E35.21553
G1 X-72.261 Y4.739 E35.23455
G1 X-89.021 Y4.739 E35.90144
;WIDTH:0.561339
G1 X-89.081 Y4.739 E35.90403
;WIDTH:0.601217
G1 X-89.141 Y4.739 E35.90682
;WIDTH:0.641095
G1 X-89.201 Y4.739 E35.9098
G1 X-89.221 Y4.819 E35.9139
;WIDTH:0.601217
G1 X-89.241 Y4.899 E35.91773
;WIDTH:0.561339
G1 X-89.261 Y4.979 E35.92128
;WIDTH:0.52146
G1 X-89.261 Y49.021 E37.67374
;WIDTH:0.562513
G1 X-89.24 Y49.121 E37.67815
;WIDTH:0.603565
G1 X-89.22 Y49.22 E37.68286
G1 X-89.121 Y49.24 E37.68757
;WIDTH:0.562513
G1 X-89.021 Y49.261 E37.69198
;WIDTH:0.52146
G1 X-9.979 Y49.261 E40.83712
;WIDTH:0.561339
G1 X-9.899 Y49.241 E40.84067
;WIDTH:0.601217
G1 X-9.819 Y49.221 E40.8445
;WIDTH:0.641095
G1 X-9.739 Y49.201 E40.8486
G1 X-9.739 Y49.141 E40.85158
;WIDTH:0.601217
G1 X-9.739 Y49.081 E40.85437
;WIDTH:0.561339
G1 X-9.739 Y49.021 E40.85696
;WIDTH:0.52146
G1 X-9.739 Y4.979 E42.60942
;WIDTH:0.561339
G1 X-9.759 Y4.899 E42.61297
;WIDTH:0.601217
G1 X-9.779 Y4.819 E42.6168
;WIDTH:0.641095
G1 X-9.799 Y4.739 E42.6209
G1 X-9.859 Y4.739 E42.62388
;WIDTH:0.601217
G1 X-9.919 Y4.739 E42.62667
;WIDTH:0.561339
G1 X-9.979 Y4.739 E42.62926
;WIDTH:0.52146
G1 X-24.739 Y4.739 E43.21657
G1 X-24.739 Y4.261 E43.23559
G1 X-9.979 Y4.261 E43.8229
;WIDTH:0.561339
G1 X-9.919 Y4.261 E43.82549
;WIDTH:0.601217
G1 X-9.859 Y4.261 E43.82828
;WIDTH:0.641095
G1 X-9.799 Y4.261 E43.83126
G1 X-9.779 Y4.181 E43.83536
;WIDTH:0.601217
G1 X-9.759 Y4.101 E43.83919
;WIDTH:0.561339
G1 X-9.739 Y4.021 E43.84274
;WIDTH:0.52146
G1 X-9.739 Y-4.739 E44.19131
G1 X-9.261 Y-4.739 E44.21033
G1 X-9.261 Y4.021 E44.5589
;WIDTH:0.561339
G1 X-9.281 Y4.181 E44.56585
;WIDTH:0.601217
G1 X-9.301 Y4.34 E44.57329
;WIDTH:0.641095
G1 X-9.321 Y4.5 E44.58131
G1 X-9.301 Y4.66 E44.58933
;WIDTH:0.601217
G1 X-9.281 Y4.819 E44.59677
;WIDTH:0.561339
G1 X-9.261 Y4.979 E44.60372
;WIDTH:0.52146
G1 X-9.261 Y49.021 E46.35618
;WIDTH:0.561339
G1 X-9.261 Y49.081 E46.35877
;WIDTH:0.601217
G1 X-9.261 Y49.141 E46.36156
;WIDTH:0.641095
G1 X-9.261 Y49.201 E46.36454
G1 X-9.181 Y49.221 E46.36864
;WIDTH:0.601217
G1 X-9.101 Y49.241 E46.37247
;WIDTH:0.561339
G1 X-9.021 Y49.261 E46.37602
;WIDTH:0.52146
G1 X30.021 Y49.261 E47.92953
;WIDTH:0.561339
G1 X30.101 Y49.241 E47.93308
;WIDTH:0.601217
G1 X30.181 Y49.221 E47.93691
;WIDTH:0.641095
G1 X30.261 Y49.201 E47.94101
G1 X30.261 Y49.141 E47.94399
;WIDTH:0.601217
G1 X30.261 Y49.081 E47.94678
;WIDTH:0.561339
G1 X30.261 Y49.021 E47.94937
;WIDTH:0.52146
G1 X30.261 Y5.979 E49.66204
;WIDTH:0.561339
G1 X30.241 Y5.899 E49.66559
;WIDTH:0.601217
G1 X30.221 Y5.819 E49.66942
;WIDTH:0.641095
G1 X30.201 Y5.739 E49.67352
G1 X25.554 Y5.739 E49.90465
;WIDTH:0.601217
G1 X20.907 Y5.739 E50.12038
;WIDTH:0.561339
G1 X16.261 Y5.739 E50.32065
;WIDTH:0.52146
G1 X16.261 Y5.261 E50.33967
G1 X30.021 Y5.261 E50.88719
;WIDTH:0.561339
G1 X30.081 Y5.261 E50.88978
;WIDTH:0.601217
G1 X30.141 Y5.261 E50.89257
;WIDTH:0.641095
G1 X30.201 Y5.261 E50.89555
G1 X30.221 Y5.181 E50.89965
;WIDTH:0.601217
G1 X30.241 Y5.101 E50.90348
;WIDTH:0.561339
G1 X30.261 Y5.021 E50.90703
;WIDTH:0.52146
G1 X30.261 Y-10.739 E51.53413
G1 X30.739 Y-10.739 E51.55315
G1 X30.739 Y5.021 E52.18025
;WIDTH:0.561339
G1 X30.719 Y5.181 E52.1872
;WIDTH:0.601217
G1 X30.699 Y5.34 E52.19464
;WIDTH:0.641095
G1 X30.679 Y5.5 E52.20266
G1 X30.699 Y5.66 E52.21068
;WIDTH:0.601217
G1 X30.719 Y5.819 E52.21812
;WIDTH:0.561339
G1 X30.739 Y5.979 E52.22507
;WIDTH:0.52146
G1 X30.739 Y49.021 E53.93774
;WIDTH:0.561339
G1 X30.739 Y49.081 E53.94033
;WIDTH:0.601217
G1 X30.739 Y49.141 E53.94312
;WIDTH:0.641095
G1 X30.739 Y49.201 E53.9461
G1 X30.819 Y49.221 E53.9502
;WIDTH:0.601217
G1 X30.899 Y49.241 E53.95403
;WIDTH:0.561339
G1 X30.979 Y49.261 E53.95758
;WIDTH:0.52146
G1 X89.021 Y49.261 E56.26712
;WIDTH:0.562512
G1 X89.121 Y49.24 E56.27153
;WIDTH:0.603564
G1 X89.22 Y49.22 E56.27624
G1 X89.24 Y49.121 E56.28095
;WIDTH:0.562512
G1 X89.261 Y49.021 E56.28536
;WIDTH:0.52146
G1 X89.261 Y-10.021 E58.63469
;WIDTH:0.561339
G1 X89.241 Y-10.101 E58.63824
;WIDTH:0.601217
G1 X89.221 Y-10.181 E58.64207
;WIDTH:0.641095
G1 X89.201 Y-10.261 E58.64617
G1 X89.141 Y-10.261 E58.64915
;WIDTH:0.601217
G1 X89.081 Y-10.261 E58.65194
;WIDTH:0.561339
G1 X89.021 Y-10.261 E58.65453
;WIDTH:0.52146
G1 X56.261 Y-10.261 E59.95808
G1 X56.261 Y-10.739 E59.9771
G1 X88.571 Y-10.739 E61.26274
G1 E59.26274 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 59.26
; filament used [cm3] = 0.14
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 54s
; estimated printing time (silent mode) = 54s
; estimated first layer printing time (normal mode) = 54s
; estimated first layer printing time (silent mode) = 54s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = -600x-600,600x-600,600x600,-600x600
; bed_temperature = 50
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "My Settings"
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 50
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 220
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 0.4
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 3
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = My Settings
; printer_model = 
; printer_notes = 
; printer_settings_id = rbtPlotter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 40
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 40
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 1
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 220
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end